FROM ubuntu:latest
LABEL maintainer="info@zopyx.com"

ENV TZ=Europe/Kiev
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt update; apt upgrade -y; \
    apt-get install -y build-essential python3-dev python3-pip python3-setuptools \
        python3-wheel python3-cffi libcairo2 libpango-1.0-0 libpangocairo-1.0-0 \
        php libgdk-pixbuf2.0-0 libffi-dev shared-mime-info python3-dev python3-venv \
        php7.4-xml php-gd default-jre \ 
        alien rpl wget npm unzip curl tini; \
    apt-get clean

ADD chromium.pref /etc/apt/preferences.d/chromium.pref
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

RUN echo "deb http://deb.debian.org/debian buster main" >> /etc/apt/sources.list.d/debian.list && \
 echo "deb http://deb.debian.org/debian buster-updates main" >> /etc/apt/sources.list.d/debian.list && \
 echo "deb http://deb.debian.org/debian-security buster/updates main" >> /etc/apt/sources.list.d/debian.list && \
 apt-key adv --keyserver keyserver.ubuntu.com --recv-keys DCC9EFBF77E11517 && \
 apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138 && \
 apt-key adv --keyserver keyserver.ubuntu.com --recv-keys AA8E81B4331F7F50 && \
 apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 112695A0E562B32A && \
 apt update && \
 apt install chromium -y && \
 apt-get clean && rm -rf /var/cache/apk/*

# Set user and group
ARG user=appuser
ARG group=appuser
ARG uid=1000
ARG gid=1000
RUN groupadd -g ${gid} ${group}
RUN useradd -u ${uid} -g ${group} -s /bin/sh -m ${user} # <--- the '-m' create a user home directory

RUN python3 -m venv /tmp/python
RUN /tmp/python/bin/pip3 install --no-cache wheel pp.server hypercorn weasyprint

RUN wget -q -O prince.deb https://www.princexml.com/download/prince_14.2-1_ubuntu20.04_amd64.deb; \
    apt install -y ./prince.deb; \
    rm prince.deb
RUN wget -q -O speedata.zip https://download.speedata.de/dl/speedata-publisher-linux-amd64-4.4.0.zip; \
    unzip speedata.zip; \
    rm speedata.zip


RUN export PUPPETEER_SKIP_DOWNLOAD='true' && npm install   pagedjs-cli
RUN export PUPPETEER_SKIP_DOWNLOAD='true' && npm install   @vivliostyle/cli


# Antennahouse
ARG AH_DOWNLOAD
ENV AH_DOWNLOAD=$AH_DOWNLOAD
RUN wget -q -O ah.rpm.gz ${AH_DOWNLOAD} ; \
        gzip -d ah.rpm; \
        alien -i ah.rpm; \
        rm ah.rpm; \
        rpl '@@HOME@@' '/usr/AHFormatterV72' /usr/AHFormatterV72/run.sh
COPY AHFormatter.lic /usr/AHFormatterV72/etc/AHFormatter.lic
RUN chmod a+r  /usr/AHFormatterV72/etc/AHFormatter.lic

# Typeset.sh
ARG TS_DOWNLOAD
ENV TS_DOWNLOAD=$TS_DOWNLOAD
RUN echo $TS_DOWNLOAD
RUN wget -q -O /usr/bin/typeset.sh.phar ${TS_DOWNLOAD} ; \
    chmod +x /usr/bin/typeset.sh.phar; 

# Calibre
RUN wget -q -nv -O- https://download.calibre-ebook.com/linux-installer.sh | bash /dev/stdin

# PDFreactor
RUN wget -q -O pdfreactor.tgz "https://www.pdfreactor.com/download/get/?product=pdfreactor&type=unix_installer&jre=false"; \
    tar xfvz pdfreactor.tgz; \
    rm pdfreactor.tgz

ADD pdfreactor.sh /
ADD licensekey.txt /PDFreactor/jetty/lib/ext
RUN chown -R ${uid}:${gid} /PDFreactor


ADD start-server.sh /
RUN chmod a+rx /start-server.sh

USER ${uid}:${gid}
EXPOSE 8000/tcp
ENTRYPOINT ["tini", "-p", "SIGKILL", "-v", "--", "/start-server.sh"]
